// Package errata is auto-generated by errata
package errata

import "fmt"

type Error struct {
	Code       string
	Message    string
	Cause      string
	Categories []string
	Labels     map[string]string
	Interfaces interfaces

	inner error
}

type interfaces struct {
	HTTPResponseCode int
	ShellExitCode    int
}

func (e Error) Unwrap() error {
	return e.inner
}

func (e Error) Error() string {
	if w := e.Unwrap(); w != nil {
		return fmt.Sprintf("[code: %s] %s", e.Code, w)
	}

	return e.Code
}

const (
	ErrCodeGenError        = "code_gen_error"
	ErrFileNotFound        = "file_not_found"
	ErrFileNotReadable     = "file_not_readable"
	ErrInvalidDatasource   = "invalid_datasource"
	ErrSyntaxError         = "syntax_error"
	ErrTemplateExecution   = "template_execution"
	ErrTemplateNotFound    = "template_not_found"
	ErrTemplateNotReadable = "template_not_readable"
	ErrTemplateSyntax      = "template_syntax"
)

func NewCodeGenError(inner error) Error {
	return Error{
		inner:      inner,
		Code:       ErrCodeGenError,
		Message:    "Code generation failed",
		Cause:      "",
		Categories: []string{"codegen"},
		Labels:     map[string]string{},
		Interfaces: interfaces{},
	}
}

func NewFileNotFound(inner error, path interface{}) Error {
	return Error{
		inner:      inner,
		Code:       ErrFileNotFound,
		Message:    fmt.Sprintf("YML file [%s] is incorrect or inaccessible", path),
		Cause:      "",
		Categories: []string{"file"},
		Labels:     map[string]string{},
		Interfaces: interfaces{},
	}
}

func NewFileNotReadable(inner error, path interface{}) Error {
	return Error{
		inner:      inner,
		Code:       ErrFileNotReadable,
		Message:    fmt.Sprintf("YML file [%s] is unreadable", path),
		Cause:      "",
		Categories: []string{"file"},
		Labels:     map[string]string{},
		Interfaces: interfaces{},
	}
}

func NewInvalidDatasource(inner error, datasource interface{}) Error {
	return Error{
		inner:      inner,
		Code:       ErrInvalidDatasource,
		Message:    fmt.Sprintf("Configured datasource [%s] is invalid", datasource),
		Cause:      "",
		Categories: []string{"init"},
		Labels:     map[string]string{},
		Interfaces: interfaces{},
	}
}

func NewSyntaxError(inner error, path interface{}) Error {
	return Error{
		inner:      inner,
		Code:       ErrSyntaxError,
		Message:    fmt.Sprintf("YML file [%s] is malformed", path),
		Cause:      "",
		Categories: []string{"parsing"},
		Labels:     map[string]string{},
		Interfaces: interfaces{},
	}
}

func NewTemplateExecution(inner error) Error {
	return Error{
		inner:      inner,
		Code:       ErrTemplateExecution,
		Message:    "Error in template execution",
		Cause:      "Possible use of missing or renamed field",
		Categories: []string{"codegen"},
		Labels:     map[string]string{},
		Interfaces: interfaces{HTTPResponseCode: 300, ShellExitCode: 3},
	}
}

func NewTemplateNotFound(inner error, path interface{}) Error {
	return Error{
		inner:      inner,
		Code:       ErrTemplateNotFound,
		Message:    fmt.Sprintf("Template path [%s] is incorrect or inaccessible", path),
		Cause:      "",
		Categories: []string{"file"},
		Labels:     map[string]string{},
		Interfaces: interfaces{},
	}
}

func NewTemplateNotReadable(inner error, path interface{}) Error {
	return Error{
		inner:      inner,
		Code:       ErrTemplateNotReadable,
		Message:    fmt.Sprintf("Template path [%s] is unreadable", path),
		Cause:      "",
		Categories: []string{"file"},
		Labels:     map[string]string{},
		Interfaces: interfaces{},
	}
}

func NewTemplateSyntax(inner error) Error {
	return Error{
		inner:      inner,
		Code:       ErrTemplateSyntax,
		Message:    "Syntax error in template",
		Cause:      "",
		Categories: []string{"codegen"},
		Labels:     map[string]string{},
		Interfaces: interfaces{ShellExitCode: 2},
	}
}
